# Generated by Django 4.1 on 2023-04-01 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.BooleanField(
                        default=True, help_text="Receive notification by email"
                    ),
                ),
                (
                    "push_notification",
                    models.BooleanField(
                        default=True, help_text="Receive notification by app"
                    ),
                ),
                (
                    "article_notification",
                    models.BooleanField(
                        default=True,
                        help_text="Receive article notification",
                        verbose_name="Article Notice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Make sure your image size atleast 1366x768px and 72 DPI resolution.",
                        null=True,
                        upload_to="",
                        verbose_name="image",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                ("action_url", models.URLField(verbose_name="Action URL")),
                (
                    "action_title",
                    models.CharField(max_length=255, verbose_name="Action Title"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last sent",
                    ),
                ),
                (
                    "sent_counter",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Counter"
                    ),
                ),
                (
                    "media",
                    models.CharField(
                        choices=[
                            ("notification", "Notification"),
                            ("email", "Email"),
                            ("android_notification", "Android Notification"),
                            ("all", "All"),
                        ],
                        default="notification",
                        max_length=255,
                        verbose_name="media",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="apps.application",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Group of recipients",
                        related_name="broadcasts",
                        to="auth.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Recipients",
                        related_name="broadcasts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast",
                "verbose_name_plural": "Broadcasts",
            },
        ),
        migrations.CreateModel(
            name="ApplicationPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("FCM", "Firebase"),
                            ("APNS", "Apple"),
                            ("GCM", "Google"),
                            ("WNS", "Windows"),
                            ("WP", "Web Push"),
                        ],
                        db_index=True,
                        default="FCM",
                        max_length=5,
                        verbose_name="Platform",
                    ),
                ),
                ("configs", models.JSONField(verbose_name="Configs")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platforms",
                        to="apps.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("promotion", "Promotion"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("actor_object_id", models.CharField(max_length=255)),
                ("verb", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("target", models.JSONField(blank=True, null=True)),
                ("action", models.JSONField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("unread", models.BooleanField(db_index=True, default=True)),
                ("public", models.BooleanField(db_index=True, default=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("notified_email", models.BooleanField(db_index=True, default=False)),
                ("notified_apns", models.BooleanField(db_index=True, default=False)),
                ("notified_gcm", models.BooleanField(db_index=True, default=False)),
                ("notified_wns", models.BooleanField(db_index=True, default=False)),
                ("notified_webpush", models.BooleanField(db_index=True, default=False)),
                (
                    "actor_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notify_actor",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="apps.application",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "index_together": {("recipient", "unread")},
            },
        ),
    ]
